### ISSUE TITLE
NotADirectoryError in resort_dataset.py

### ISSUE THREAD

**Issue by sujaykadam** [LeadingIndiaAI/Armed-Injured-and-other-Suspicious-Activity-Recognition-using-Drone-Surveillance#1]
The resort_dataset.py throws an error :- NotADirectoryError: [WinError 267] The directory name is invalid: 'DCSASS Dataset/Abuse/Abuse001_x264_10.mp4/' on line 12 "for clip in os.listdir(subfolder_url):" Some problem with subfolder_url, help me understand the directory structure.

**Comment by mitushiagarwal9** [comment]
> The resort_dataset.py throws an error :- NotADirectoryError: [WinError 267] The directory name is invalid: 'DCSASS Dataset/Abuse/Abuse001_x264_10.mp4/' on line 12 "for clip in os.listdir(subfolder_url):" Some problem with subfolder_url, help me understand the directory structure.
How this to resolve this issue? Even I am getting this error.
